---
- name: Deploy ArgoCD to Kubernetes cluster
  hosts: system
  become: yes
  vars:
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

  tasks:
    - name: Ensure Kubernetes namespace exists
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: argocd

    - name: Add Argo Helm repo
      community.kubernetes.helm_repository:
        name: argo
        repo_url: https://argoproj.github.io/argo-helm

    - name: Install ArgoCD via Helm with tolerations
      community.kubernetes.helm:
        name: argocd
        chart_ref: argo/argo-cd
        release_namespace: argocd
        kubeconfig: "{{ kubeconfig_path }}"
        create_namespace: false
        values:
          controller:
            tolerations:
              - key: "node-role"
                operator: "Equal"
                value: "system"
                effect: "NoSchedule"
              - key: "dedicated.deckhouse.io"
                operator: "Equal"
                value: "system"
                effect: "NoExecute"

          repoServer:
            tolerations:
              - key: "node-role"
                operator: "Equal"
                value: "system"
                effect: "NoSchedule"
              - key: "dedicated.deckhouse.io"
                operator: "Equal"
                value: "system"
                effect: "NoExecute"

          server:
            tolerations:
              - key: "node-role"
                operator: "Equal"
                value: "system"
                effect: "NoSchedule"
              - key: "dedicated.deckhouse.io"
                operator: "Equal"
                value: "system"
                effect: "NoExecute"

          applicationSet:
            tolerations:
              - key: "node-role"
                operator: "Equal"
                value: "system"
                effect: "NoSchedule"
              - key: "dedicated.deckhouse.io"
                operator: "Equal"
                value: "system"
                effect: "NoExecute"