---
- name: Create GitLab project
  ansible.builtin.uri:
    url: "{{ gitlab_url }}/api/v4/projects"
    method: POST
    headers:
      Private-Token: "{{ gitlab_access_token }}"
      Content-Type: "application/json"
    body: "{{ lookup('template', 'project_config.json.j2') }}"
    body_format: json
    status_code: 201
    validate_certs: "{{ gitlab_validate_certs | default(false) }}"
  register: project_creation
  tags: project

- name: Debug project creation result
  ansible.builtin.debug:
    msg: "Project created with ID {{ project_creation.json.id }}"
  when: project_creation.json.id is defined
  tags: project