all:
  vars:
    kube_apiserver: "91.217.196.189:6443"   # Замените на ваш адрес API-сервера
    token: "eyJhbGciOiJSUzI1NiIsImtpZCI6Ik00Wm1lZFBOdTJCTVlaaWs1aktIaFZxSjZnaE12eE9Cc2lmSW9vbFNCeDgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzUyODM3OTIxLCJpYXQiOjE3NTI4MzQzMjEsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYzIzMmFlNzUtYWUxNS00OTMwLWI2ZTItMmFlZGZmN2NmN2IzIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkOC1jbG91ZC1pbnN0YW5jZS1tYW5hZ2VyIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6Im5vZGUtZ3JvdXAiLCJ1aWQiOiI1OTBhYTJjOS0xZDdmLTQxM2MtYTliZi0xNGNhYTk0M2RhNDYifX0sIm5iZiI6MTc1MjgzNDMyMSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmQ4LWNsb3VkLWluc3RhbmNlLW1hbmFnZXI6bm9kZS1ncm91cCJ9.rxqhypzza5Hr7qnWgtpVz68jllrLkcTXGImDjfueFB2AAvUOOjR6V8fFp1Z2pDcDwG16qfJaPFp8pVQqQh5kzXBApWqfhvIC2hc0KP-Ht4ET3dLHW6e2jc2tcaq4MCikinfx5b00y8WCVhcqPYKQv5ETAb96CmWfvET4VMYBUcBQQX8N52SvDnwLcov9N_Hx-A7QC6cMNK166cza5LFEHW2V3sHYnKUAIIsWWfbaMNSyAbLw5ucfANs9iJxefbry51Cw71NXWECQ2GgJRoXGCKR6jMR5O_OqkmVz01J1WoF6m6K7vTs9nE3aVV-DrTK2_kCZsZ17Z29mu7oenTwFng"  # Замените на полученный токен

  children:
    master:
      hosts: 
        master: 
          ansible_host:  91.217.196.189
          ansible_user: vrstel
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    worker:
      hosts:
        worker-n1:
          ansible_host: 192.168.39.58
          ansible_user: loginov
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        worker-n2:
          ansible_host: 91.217.196.152
          ansible_user: haproxy
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

      vars:
        node_group: worker

    system:
      hosts:
        system:
          ansible_host: 91.217.196.183
          ansible_user: sunofthetruth
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

      vars:
        node_group: system