all:
  vars:
    kube_apiserver: "91.217.196.189:6443"   # Замените на ваш адрес API-сервера
    token: "eyJhbGciOiJSUzI1NiIsImtpZCI6Ik00Wm1lZFBOdTJCTVlaaWs1aktIaFZxSjZnaE12eE9Cc2lmSW9vbFNCeDgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzUyODMwOTgyLCJpYXQiOjE3NTI4MjczODIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYWIwODkwMzMtNjc5NC00Yjk0LTgyOGItYTE4MjhhYTM1OWZlIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkOC1jbG91ZC1pbnN0YW5jZS1tYW5hZ2VyIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6Im5vZGUtZ3JvdXAiLCJ1aWQiOiI1OTBhYTJjOS0xZDdmLTQxM2MtYTliZi0xNGNhYTk0M2RhNDYifX0sIm5iZiI6MTc1MjgyNzM4Miwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmQ4LWNsb3VkLWluc3RhbmNlLW1hbmFnZXI6bm9kZS1ncm91cCJ9.wUkyjCyC8i8fCLY6wypd1RBZki6L-mUdyH_2zzQNWz_Dthxs6D5u8O2jRaWmVOWAftWMDKy-9UMdugNfO_llNYr-8jsUbgcNJaZLmIUYGuPAaHjzkaP7xGsQAAV58RuuTcNvQHiiPyYDzzZXPJbDlRdJaEAZJ25EzF--poLnVlbVYGg4STFUBPZisHZ1gC-pH90NLadvHg5_0ln-7j0m5zRlAmYjXuxlsj4pJCBoezBMQ5O5cZDAXCtdT06IrbU1tSzsAI6aIQsQwBpiqxJeStlPwDRAItFdHGD9feSBxf-BkXXEPhhu0VDsuiZaBWhSW8cfgJvvicb96fofC9ezqg"  # Замените на полученный токен

  children:
    worker:
      hosts:
        worker-n1:
          ansible_host: 192.168.39.58
          ansible_user: loginov
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        worker-n2:
          ansible_host: 91.217.196.152
          ansible_user: haproxy
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

      vars:
        node_group: worker

    system:
      hosts:
        system:
          ansible_host: 91.217.196.183
          ansible_user: sunofthetruth
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

      vars:
        node_group: system